### ISSUE TITLE
Please remove dependency on yasnippet-bundle

### ISSUE THREAD

**Issue by tarsius** [mattfidler/el-autoyas.el#4]
`yasnippet-bundle` is... gone. I would tell you more if I knew, but unfortunately https://github.com/joaotavora/yasnippet/commit/483364c8e51214d96d196c2966083889138ab8b3 is all I could find on the matter.

@npostavs any insights on this?

**Comment by tarsius** [comment]
Please do the same for `extend-dnd` and `r-autoyas`.

**Comment by npostavs** [comment]
> @npostavs any insights on this?

Not really, it was removed before I started contributing to yasnippet. AFAIK, `yas-compile-snippets` now implements similar functionality (that is, it puts a bunch of snippets into a single file).

**Comment by mattfidler** [comment]
The current treatment uses

```lisp
(require 'yasnippet-bundle nil t)
```
which will not require the library, unless it is present.  This should allow for backward-compatability.  Shouldn't this be sufficient for your needs?

**Comment by mattfidler** [comment]
The same is true for `el-autoyas` and `extend-dnd`

**Comment by tarsius** [comment]
> Shouldn't this be sufficient for your needs?

My "need" is that I maintain the Emacsmirror and look into all dependency issues, which often involves contacting upstream.

"I want to keep this for backward compatibility" is good enough an answer for me. Since the Emacsmirror (like Melpa) is focused on the latest versions of all packages, I will explicitly drop the dependency on this obsolete library. Otherwise users would wounder "well, it's a soft dependency, so I don't *need* it, but what am I missing out on?".

On the other hand, are you sure these packages still work properly with recent `yasnippet` releases?

**Comment by mattfidler** [comment]
Yes they work.  I use them on recent versions.

**Comment by tarsius** [comment]
Great! All good then. Thanks for your time.
